### ISSUE TITLE
Docs for implementing other query providers

### ISSUE THREAD

**Issue by hy9be** [gordonwoodhull/nanofilter#2]
I am interested in implementing an ``Apache Arrow`` and ``Mapd`` backed query engine conforming to the interface of xfilter. It looks the interface would be the 3 functions named ``do_query``, ``unpack_result``, and ``fetch_schema``. Is that right? Are there any documentations help me to understand the expected input and output of these functions? Thanks.

PS: I am aware that the issue tab is not for communication like this. But did not find any other ways. Please bear with me on it.

**Comment by gordonwoodhull** [comment]
Hi @hy9be! 

Indeed there is not a lot of documentation on how to implement new backends. So your question is entirely appropriate.

I have started documenting the interface [in the wiki](https://github.com/att/xfilter/wiki/Implementing-a-query-provider-backend). 

Please raise any questions here, or feel free to edit the wiki if you find mistakes or details missing.

This project is experimental - I started it because I saw a lot of hacky implementations of dc.js connected to alternative backends, and wanted to show a safer way to do it.

However, since it is only based on two query provider implementations, there may be stuff missing or not general enough to connect with other query providers. I'll be happy to work with you to fix any deficiencies - please raise issues here, or if you want to fork and raise pull requests, that is very welcome too!

**Comment by hy9be** [comment]
@gordonwoodhull thanks for the reply. I would love to help on this. Will contact you offline through email.
